---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install td-agent.
  package:
    name: td-agent
    state: "{{ fluentd_package_state }}"

- name: FLUENTD | Create server conf path
  file:
    path: "{{ fluentd_conf_path }}"
    state: directory
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_group }}"
    mode: 0755

- name: FLUENTD | Create log path
  file:
    path: "{{ fluentd_log_path }}"
    state: directory
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_group }}"
    mode: 0755

- name: FLUENTD | Copy server config
  template:
    src: "{{ fluentd_playbook_templates_path }}/td-agent.conf.j2"
    dest: "{{ fluentd_conf_path }}/tg-agent.conf"
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_group }}"
    mode: 0644
  notify: restart fluentd

- name: Configure Fluentd.
  template:
    src: td-agent.conf.j2
    dest: /etc/td-agent/td-agent.conf
    owner: "{{ fluentd_user }}"
    group: "{{ fluentd_group }}"
    mode: 0644
  notify: restart fluentd

- name: Ensure Fluentd plugins are installed.
  gem:
    name: "{{ item.name | default(item) }}"
    executable: /opt/td-agent/embedded/bin/fluent-gem
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    user_install: false
  with_items: "{{ fluentd_plugins }}"

- name: Start Fluentd.
  service:
    name: "{{ fluentd_service_name }}"
    state: "{{ fluentd_service_state }}"
    enabled: "{{ fluentd_service_enabled }}"
